# PHP7-FPM
FROM php:7-fpm
MAINTAINER EasyPath IT Solutions Inc. <info@easypath.ca>

ENV web_root /webapps/wordpress

# Install OS utilities
RUN apt-get update
RUN apt-get -y install \
  curl \
  iputils-ping \
  net-tools \
  git \
  zip \
  unzip \
  wget \
  vim \
  mysql-client

# Install WP-CLI
ENV wpcli_dir /usr/local/bin
RUN curl -o ${wpcli_dir}/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x ${wpcli_dir}/wp
RUN wp --info --allow-root

# Enable PHP core extensions
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng12-dev \
    && docker-php-ext-install -j$(nproc) iconv mcrypt \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install mysqli \
    && docker-php-ext-install zip
