version: '2'

services:
  db:
    image: mariadb:latest
    volumes:
      - "./db:/var/lib/mysql"
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
     MYSQL_DATABASE: $MYSQL_DATABASE
     MYSQL_USER: $MYSQL_USER
     MYSQL_PASSWORD: $MYSQL_PASSWORD

  php:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-php7fpm-wordpress
    image: easypath/php7-fpm-wordpress:latest
    restart: always
    volumes:
      - ./site:/webapps/wordpress/site

  nginx:
    depends_on:
      - php
    build:
      context: .
      dockerfile: Dockerfile-nginx-wordpress
    image: easypath/nginx-wordpress:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./site:/webapps/wordpress/site
    links:
        - php